### PR TITLE
refactor: filterNoMatchReason and shouldSkipRequest

### PR DESCRIPTION
**Pull request by btlghrants**
## Description

`src/lib/helpers.ts` and `src/lib/filter.ts` are becoming unwieldy -- this PR is intended to make them simpler to grok / move forward on.

## Related Issue

Fixes # https://github.com/defenseunicorns/pepr/issues/1154

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging
- [x] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [x] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

### CODE REVIEW

**Comment by btlghrants** [comment]
As I started working from a branch-of-a-branch ( while waiting for team member to finish-up working in the same part of the code base this PR touches ) I had to rewrite a little history in order to roll their changes into mine -- lost a bunch of intermediate commits covering the filterNoMatchReason logic extraction, but all the refactored codes still here, for sure.

**Comment by btlghrants** [comment]
Found some minor issues in a couple of our test fixtures -- src/fixtures/data/create-pod.json / src/fixtures/data/delete-pod.json -- and am just going to roll the corrections into this PR so that the refactored tests still function as expected.

**Comment by btlghrants** [comment]
I moved all the comparisons / "should this binding apply or not"-type code into a single file -- `adjudicators.ts` as in, adjudicator: "one who makes a formal judgment or decision about a problem" (the "problem" being whether a binding applies to a Watched / Admitted KubernetesObject or not) -- since both filter.ts & helpers.ts had about equal claim on them.

Not hard-set on the naming of the file though. Happy do discuss it if anyone feels strongly about calling it something else.

**Comment by cmwylie19** [comment]
e2e test:
- [x] hello-pepr-ns-all
- [x] hello-pepr-ns-bounded
- [x] hello-pepr-ns-wrong
- [x] hello-pepr-mutate

**Review by cmwylie19 — APPROVED** [review]

**Pull request merged**
