### PR TITLE
docs: add contributor covenant code of conduct

### PR DESCRIPTION
**Pull request by salaxander**
## Description
It's good practice to have a code of conduct in the repo (and will be required if Pepr moves to CNCF). Adopting the contributor covenant is a good starting point.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/contributor-guide/#submitting-a-pull-request) followed

### CODE REVIEW

**Comment by salaxander** [comment]
No idea why CI is grumpy on this one 🙃. Any ideas @cmwylie19?

**Comment by schaeferka** [comment]
Is this in addition to the Code of Conduct we have at [https://github.com/defenseunicorns/pepr/blob/main/docs/120_contribute/020_code-of-conduct.md](https://github.com/defenseunicorns/pepr/blob/main/docs/120_contribute/020_code-of-conduct.md)?

**Review by cmwylie19 — APPROVED** [review]

**Comment by cmwylie19** [comment]
> No idea why CI is grumpy on this one 🙃. Any ideas @cmwylie19?

deprecation in Node.js v22.0.0 :) , should be good now

**Comment by cmwylie19** [comment]
@salaxander do you think we should consolidate our code of conducts? or create a separate one?

**Comment by salaxander** [comment]
> @salaxander do you think we should consolidate our code of conducts? or create a separate one?

So I hadn't noticed the one @schaeferka pointed out. It looks like it's also contributor covenant. We should definitely have one in a markdown file in the repo root. So options would be:

1) Keep both the new markdown file and the website page
2) Delete the website page in favor of the new markdown file

Personally, I think it's fine to keep it referenced in both places.

**Comment by schaeferka** [comment]
If we want to have it only in one place to keep things easier to maintain, we'll need to take a look at how we have our docs site set up to see if we can modify it so that it pulls the content from the code of conduct in the main repo into the correct section of the docs. I think we do something similar for the docs home page and the main README.md file, but I'll need to take a look at it.

**Comment by schaeferka** [comment]
@salaxander Are there any other markdown files that we should have in root? If so, it may make sense to go ahead and add them to the root directory while we're doing the contributor guide.

**Comment by salaxander** [comment]
> @salaxander Are there any other markdown files that we should have in root? If so, it may make sense to go ahead and add them to the root directory while we're doing the contributor guide.

The other one we should probably have is a `SUPPORT.md` file that highlights when to file an issue vs when to reach out directly etc.

**Comment by cmwylie19** [comment]
Thanks @salaxander @schaeferka , for the sake of this issue, i believe it is now complete. We will  discuss in standup if it makes sense to have the docs site pull this code directly into the website.

[Issue](https://github.com/defenseunicorns/pepr/issues/764) for `SUPPORT.md`

**Review by cmwylie19 — DISMISSED** [review]

**Comment by cmwylie19** [comment]
Hey @salaxander the only problem now is that your commit is not signed. Would you mind signing it?

**Review by cmwylie19 — APPROVED** [review]

**Pull request merged**
